inherit_from: .rubocop_todo.yml
AllCops:
  #Include:
  Exclude:
    - '**/Rakefile'
    - '**/config.ru'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
